package org.mykanna.school.entity;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.id
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.login_name
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	private String loginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.name
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.password
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.salt
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	private String salt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.role_id
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.grade
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	private String grade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.code
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.certificate
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	private String certificate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.phone
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.email
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.wechat_open_id
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	private String wechatOpenId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.credit
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	private Integer credit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.user_approve
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	private Boolean userApprove;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.register_time
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	private Date registerTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.is_delete
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	private Boolean isDelete;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.id
	 * @return  the value of tb_user.id
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.id
	 * @param id  the value for tb_user.id
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.login_name
	 * @return  the value of tb_user.login_name
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.login_name
	 * @param loginName  the value for tb_user.login_name
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.name
	 * @return  the value of tb_user.name
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.name
	 * @param name  the value for tb_user.name
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.password
	 * @return  the value of tb_user.password
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.password
	 * @param password  the value for tb_user.password
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.salt
	 * @return  the value of tb_user.salt
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.salt
	 * @param salt  the value for tb_user.salt
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public void setSalt(String salt) {
		this.salt = salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.role_id
	 * @return  the value of tb_user.role_id
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.role_id
	 * @param roleId  the value for tb_user.role_id
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.grade
	 * @return  the value of tb_user.grade
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public String getGrade() {
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.grade
	 * @param grade  the value for tb_user.grade
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public void setGrade(String grade) {
		this.grade = grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.code
	 * @return  the value of tb_user.code
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.code
	 * @param code  the value for tb_user.code
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.certificate
	 * @return  the value of tb_user.certificate
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public String getCertificate() {
		return certificate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.certificate
	 * @param certificate  the value for tb_user.certificate
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public void setCertificate(String certificate) {
		this.certificate = certificate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.phone
	 * @return  the value of tb_user.phone
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.phone
	 * @param phone  the value for tb_user.phone
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.email
	 * @return  the value of tb_user.email
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.email
	 * @param email  the value for tb_user.email
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.wechat_open_id
	 * @return  the value of tb_user.wechat_open_id
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public String getWechatOpenId() {
		return wechatOpenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.wechat_open_id
	 * @param wechatOpenId  the value for tb_user.wechat_open_id
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public void setWechatOpenId(String wechatOpenId) {
		this.wechatOpenId = wechatOpenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.credit
	 * @return  the value of tb_user.credit
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public Integer getCredit() {
		return credit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.credit
	 * @param credit  the value for tb_user.credit
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public void setCredit(Integer credit) {
		this.credit = credit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.user_approve
	 * @return  the value of tb_user.user_approve
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public Boolean getUserApprove() {
		return userApprove;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.user_approve
	 * @param userApprove  the value for tb_user.user_approve
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public void setUserApprove(Boolean userApprove) {
		this.userApprove = userApprove;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.register_time
	 * @return  the value of tb_user.register_time
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public Date getRegisterTime() {
		return registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.register_time
	 * @param registerTime  the value for tb_user.register_time
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.is_delete
	 * @return  the value of tb_user.is_delete
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public Boolean getIsDelete() {
		return isDelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.is_delete
	 * @param isDelete  the value for tb_user.is_delete
	 * @mbg.generated  Wed Feb 21 15:57:48 CST 2018
	 */
	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}
}